### ISSUE TITLE
Error when Room was empty saved. Start -> Stop - Loop

### ISSUE THREAD

**Issue by twimon** [codmpm/node-red-contrib-loxone#6]
4 Apr 12:20:38 - [red] Uncaught Exception:
4 Apr 12:20:38 - TypeError: Cannot read property 'name' of undefined
at LoxoneMiniserver.handleEvent (/usr/lib/node_modules/node-red-contrib-loxone/loxone/loxone.js:318:79)
at API._updateEvent (/usr/lib/node_modules/node-red-contrib-loxone/loxone/loxone.js:89:18)
at emitTwo (events.js:106:13)
at API.emit (events.js:191:7)
at /usr/lib/node_modules/node-red-contrib-loxone/node_modules/node-lox-ws-api/lib/API.js:124:18
at Array.forEach (native)
at Connection.<anonymous> (/usr/lib/node_modules/node-red-contrib-loxone/node_modules/node-lox-ws-api/lib/API.js:123:18)
at emitOne (events.js:96:13)
at Connection.emit (events.js:188:7)
at Connection.handle_message (/usr/lib/node_modules/node-red-contrib-loxone/node_modules/node-lox-ws-api/lib/Connection.js:155:18)
at WebSocketConnection.<anonymous> (/usr/lib/node_modules/node-red-contrib-loxone/node_modules/node-lox-ws-api/lib/Connection.js:103:14)
at emitOne (events.js:96:13)
at WebSocketConnection.emit (events.js:188:7)
at WebSocketConnection.processFrame (/usr/lib/node_modules/node-red-contrib-loxone/node_modules/websocket/lib/WebSocketConnection.js:524:26)
at /usr/lib/node_modules/node-red-contrib-loxone/node_modules/websocket/lib/WebSocketConnection.js:321:40
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....

**Comment by codmpm** [comment]
Hmm... could you clarify how to reproduce?

To me `318` could not be undefined as this is checked in `315`.

**Comment by codmpm** [comment]
Ah, you are using `0.1.x`, so the line numbers differ. 

Should be fixed in `0.2.2`. As I don't know how to reproduce this, please get back to me if it is working now.
