### ISSUE TITLE
Reconnect to Miniserver fails sometimes after new Config File is stored to Miniserver

### ISSUE THREAD

**Issue by maxweissboeck** [codmpm/node-red-contrib-loxone#73]
Sometimes (every 5 to 10 times) Loxone Node does not reconnect to Miniserver after Miniserver restart due to deply of config file to Miniserver.

In the Node Red log File, the following can be found:

`
Websocket Connection closed: 1000 normally closed
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: normally closed (1000)
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:22 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting

...... some 100 messages ....

11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] connection closed: reconnecting
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] Miniserver connected (192.168.178.230:80) using Token-Enc
11 Jun 15:20:40 - [info] [loxone-miniserver:bda880d5.2d4e98] got structure file 2022-06-11 15:20:19
`

Then nothing more happens. No more log and still no connection.

It locks like reconnect requests happens much too fast, without any delay between the reconnects.

Only restart of Node Red solves the problem (sometimes also a redeploy of the flow helps).

Tested on:
Raspberry 4
Node Red Version V 2.2.2
Loxone Node Version 0.10.12
Miniserver Gen 2

**Comment by gahujipo** [comment]
I can confirm this behavior for my setup: 

Node Red Version V 2.2.2 running in a container from nodered/node-red
node-red-contrib-loxone version 0.10.12 
1. Miniserver: Miniserver Gen 1
2. Miniserver: Miniserver Gen 2

Keepalive: 15 seconds

**Comment by mr-manuel** [comment]
I have the same issue. Is it a problem of this node or of the `node-lox-ws-api` node (https://github.com/alladdin/node-lox-ws-api)?

Node Red Version: 3.0.2
Miniserver Gen 2 Version: 13.1.10.19

```
26 Oct 11:06:07 - [red] Uncaught Exception:
26 Oct 11:06:07 - [error] TypeError: Cannot read properties of undefined (reading 'closeDescription')
    at Connection.<anonymous> (/data/node_modules/node-lox-ws-api/lib/Connection.js:64:62)
    at WebSocketClient.emit (node:events:527:28)
    at ClientRequest.handleRequestError (/data/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by ludekvodicka** [comment]
Is there any progress with this issue, please? 

Or any chance to use keepalive/online node and manually call reconnect?

**Comment by codmpm** [comment]
@ludekvodicka Sorry, currently not. 
Hopefully in the next weeks. 

If someone wants, feel free to do a pull request.

**Comment by ludekvodicka** [comment]
> @ludekvodicka Sorry, currently not. Hopefully in the next weeks.
> 
> If someone wants, feel free to do a pull request.

Any progress please? Unfortunately the issue still occurs time to time leading to complete disconnect of my zigbee lights from loxone server.

Is there any way how to manually trigger the reconnection via some REST API for example?
