### ISSUE TITLE
Uncaught exception on regular basis

### ISSUE THREAD

**Issue by janwadebock** [codmpm/node-red-contrib-loxone#86]
I have on regular basis an uncaught exception due to which Nodered restarts completely.

Context:
I am running nodered in docker on a synology.
Running Nodered docker version 4.0.5-22 

those are the installed nodes:
![image](https://github.com/user-attachments/assets/a1816398-7a1c-42d6-a45b-89e28f867f42)

Sometimes, the nodered docker container restarts with this error message:
2024-12-02T08:13:41.597648451Z	stdout	2 Dec 08:13:41 - [red] Uncaught Exception:
2024-12-02T08:13:41.598272672Z	stdout	2 Dec 08:13:41 - [error] ReferenceError: data is not defined
2024-12-02T08:13:41.598371360Z	stdout	    at API.<anonymous> (/data/node_modules/node-red-contrib-loxone/loxone/loxone.js:263:21)
2024-12-02T08:13:41.598436433Z	stdout	    at API.emit (node:events:518:28)
2024-12-02T08:13:41.598481788Z	stdout	    at Connection.<anonymous> (/data/node_modules/node-lox-ws-api/lib/API.js:119:14)
2024-12-02T08:13:41.598536132Z	stdout	    at Connection.emit (node:events:518:28)
2024-12-02T08:13:41.598580044Z	stdout	    at Connection.handle_message (/data/node_modules/node-lox-ws-api/lib/Connection.js:176:18)
2024-12-02T08:13:41.598626870Z	stdout	    at WebSocketConnection.<anonymous> (/data/node_modules/node-lox-ws-api/lib/Connection.js:142:14)
2024-12-02T08:13:41.598676245Z	stdout	    at WebSocketConnection.emit (node:events:518:28)
2024-12-02T08:13:41.598744180Z	stdout	    at WebSocketConnection.processFrame (/data/node_modules/websocket/lib/WebSocketConnection.js:554:26)
2024-12-02T08:13:41.598793436Z	stdout	    at /data/node_modules/websocket/lib/WebSocketConnection.js:323:40
2024-12-02T08:13:41.598837317Z	stdout	    at processTicksAndRejections (node:internal/process/task_queues:85:11)

How can I debug this further ?

**Comment by codmpm** [comment]
Hey there,

which Miniserver Version are you running?

**Comment by janwadebock** [comment]
hi, sorry, should have mentioned this:
Currently I am running Loxone Config 15.2.10.14 / miniserver Gen 1
I do not see any errors in the loxone log at the same time the above error was generated

**Comment by janwadebock** [comment]
Hi, just wondering if you found anything, as I have this issue at least once, but in many cases several times a day.

**Comment by trenty27** [comment]
hi, same crash here just happened in my system (miniserver gen 1, lox config 15.5.3.4, node-red-contrib-loxone
0.10.13):

4 Jul 21:28:15 - [red] Uncaught Exception:
4 Jul 21:28:15 - [error] ReferenceError: data is not defined
    at API.<anonymous> (/data/node_modules/node-red-contrib-loxone/loxone/loxone.js:263:21)
    at API.emit (node:events:524:28)
    at Connection.<anonymous> (/data/node_modules/node-lox-ws-api/lib/API.js:119:14)
    at Connection.emit (node:events:524:28)
    at Connection.handle_message (/data/node_modules/node-lox-ws-api/lib/Connection.js:176:18)
    at WebSocketConnection.<anonymous> (/data/node_modules/node-lox-ws-api/lib/Connection.js:142:14)
    at WebSocketConnection.emit (node:events:524:28)
    at WebSocketConnection.processFrame (/data/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /data/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
4 Jul 21:28:16 - [info]
